#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

emacsclient --eval "(kill-emacs)"
mullvad disconnect

eww kill
pkill picom
pkill wired
pkill mullvad
pkill flameshot
pkill zulip
