#!/bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# unload the old theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi

# load the down script to the expected location
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

if [ -x "$(command -v feh)" ]; then
    feh --bg-scale $SCRIPTPATH/wallpaper.jpg 
fi

if [ -x "$(command -v picom)" ]; then
    picom &
fi

if [ -x "$(command -v eww)" ]; then
    eww daemon &
    eww open main &
fi

if [ -x "$(command -v wired)" ]; then
    wired &
fi

# The "current" folder is not working correctly, so i have to apply this wea.
leftwm-command "LoadTheme ~/.config/leftwm/themes/current/theme.ron"
